server:
  port: 8006

#服务别名 --- 注册consul到注册中心名称
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.45.145
      port: 8500
      discovery:
        service-name: ${spring.application.name}