server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
       - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
         #匹配后提供服务的路由地址
         #uri: http://localhost:8001
         uri: lb://cloud-payment-service
         predicates:
           - Path=/payment/get/** # 断言，路径相匹配的进行路由
       - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
           #匹配后提供服务的路由地址
         #uri: http://localhost:8001
         uri: lb://cloud-payment-service
         predicates:
           - Path=/payment/lb/** #断言,路径相匹配的进行路由
           #- After=2020-11-01T10:10:51.512+08:00[Asia/Shanghai]
           #- Before=2020-11-01T10:10:51.512+08:00[Asia/Shanghai]
           #- Cookie=username,ming
           #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
           #- Host=**.ming.com
           #- Method=POST
           #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
             # 过滤
           #filters:
           #  - AddRequestHeader=X-Request-red, blue





eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/