server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  #consul注册中心地址
  cloud:
    consul:
      host: 192.168.45.145
      port: 8500
      discovery:
        service-name: ${spring.application.name}